version: '3.8'
name: blogs_container
  
services:
  mysql_2:
    image: mysql:latest
    container_name: mysql_v2
    # restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    ports:
      - 3307:3306

  app:
    depends_on:
      - mysql_2
    build: .
    container_name: blogs_v2
    image: blogs:2
    env_file:
      - .env
    environment:
      - DATABASE_HOST=mysql_2
    ports:
      - 4000:4000
    volumes:
      # - .:/myapp
      - ./dist:/myapp/dist
